// automatically generated by the FlatBuffers compiler, do not modify

export { Color } from './my-game/sample/color.ts';
export { Equipment, unionToEquipment, unionListToEquipment } from './my-game/sample/equipment.ts';
export { Monster } from './my-game/sample/monster.ts';
export { Vec3 } from './my-game/sample/vec3.ts';
export { Weapon } from './my-game/sample/weapon.ts';
