"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.WeaponT = exports.Weapon = exports.Vec3T = exports.Vec3 = exports.MonsterT = exports.Monster = exports.unionListToEquipment = exports.unionToEquipment = exports.Equipment = exports.Color = void 0;
var color_js_1 = require("./my-game/sample/color.js");
__createBinding(exports, color_js_1, "Color");
var equipment_js_1 = require("./my-game/sample/equipment.js");
__createBinding(exports, equipment_js_1, "Equipment");
__createBinding(exports, equipment_js_1, "unionToEquipment");
__createBinding(exports, equipment_js_1, "unionListToEquipment");
var monster_js_1 = require("./my-game/sample/monster.js");
__createBinding(exports, monster_js_1, "Monster");
__createBinding(exports, monster_js_1, "MonsterT");
var vec3_js_1 = require("./my-game/sample/vec3.js");
__createBinding(exports, vec3_js_1, "Vec3");
__createBinding(exports, vec3_js_1, "Vec3T");
var weapon_js_1 = require("./my-game/sample/weapon.js");
__createBinding(exports, weapon_js_1, "Weapon");
__createBinding(exports, weapon_js_1, "WeaponT");
