"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.Color = void 0;
/**
 * The possible monster colors
 */
var Color;
(function (Color) {
    /**
     * Should be rendered the same color as blood
     */
    Color[Color["Red"] = 0] = "Red";
    /**
     * Any green will do
     */
    Color[Color["Green"] = 1] = "Green";
    /**
     * Must be `#89CFF0`
     */
    Color[Color["Blue"] = 2] = "Blue";
})(Color = exports.Color || (exports.Color = {}));
