// automatically generated by the FlatBuffers compiler, do not modify

import { Weapon, WeaponT } from '../../my-game/sample/weapon.js';


/**
 * Weapons or other equipment
 */
export enum Equipment {
  NONE = 0,

  /**
   * Equipment of the weapon-type
   */
  Weapon = 1
}

export function unionToEquipment(
  type: Equipment,
  accessor: (obj:Weapon) => Weapon|null
): Weapon|null {
  switch(Equipment[type]) {
    case 'NONE': return null; 
    case 'Weapon': return accessor(new Weapon())! as Weapon;
    default: return null;
  }
}

export function unionListToEquipment(
  type: Equipment, 
  accessor: (index: number, obj:Weapon) => Weapon|null, 
  index: number
): Weapon|null {
  switch(Equipment[type]) {
    case 'NONE': return null; 
    case 'Weapon': return accessor(index, new Weapon())! as Weapon;
    default: return null;
  }
}
