"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
exports.__esModule = true;
exports.Vec3T = exports.Vec3 = void 0;
var Vec3 = /** @class */ (function () {
    function Vec3() {
        this.bb = null;
        this.bb_pos = 0;
    }
    Vec3.prototype.__init = function (i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    };
    Vec3.prototype.x = function () {
        return this.bb.readFloat32(this.bb_pos);
    };
    Vec3.prototype.y = function () {
        return this.bb.readFloat32(this.bb_pos + 4);
    };
    Vec3.prototype.z = function () {
        return this.bb.readFloat32(this.bb_pos + 8);
    };
    Vec3.sizeOf = function () {
        return 12;
    };
    Vec3.createVec3 = function (builder, x, y, z) {
        builder.prep(4, 12);
        builder.writeFloat32(z);
        builder.writeFloat32(y);
        builder.writeFloat32(x);
        return builder.offset();
    };
    Vec3.prototype.unpack = function () {
        return new Vec3T(this.x(), this.y(), this.z());
    };
    Vec3.prototype.unpackTo = function (_o) {
        _o.x = this.x();
        _o.y = this.y();
        _o.z = this.z();
    };
    return Vec3;
}());
exports.Vec3 = Vec3;
var Vec3T = /** @class */ (function () {
    function Vec3T(x, y, z) {
        if (x === void 0) { x = 0.0; }
        if (y === void 0) { y = 0.0; }
        if (z === void 0) { z = 0.0; }
        this.x = x;
        this.y = y;
        this.z = z;
    }
    Vec3T.prototype.pack = function (builder) {
        return Vec3.createVec3(builder, this.x, this.y, this.z);
    };
    return Vec3T;
}());
exports.Vec3T = Vec3T;
