// automatically generated by the FlatBuffers compiler, do not modify

package MyGame.Sample

/**
 * The possible monster colors
 */
@Suppress("unused")
class Color private constructor() {
    companion object {
        /**
         * Should be rendered the same color as blood
         */
        const val Red: Byte = 0
        /**
         * Any green will do
         */
        const val Green: Byte = 1
        /**
         * Must be `#89CFF0`
         */
        const val Blue: Byte = 2
        val names : Array<String> = arrayOf("Red", "Green", "Blue")
        fun name(e: Int) : String = names[e]
    }
}
