// automatically generated by the FlatBuffers compiler, do not modify

package MyGame.Sample

/**
 * Weapons or other equipment
 */
@Suppress("unused")
class Equipment private constructor() {
    companion object {
        const val NONE: UByte = 0u
        /**
         * Equipment of the weapon-type
         */
        const val Weapon: UByte = 1u
        val names : Array<String> = arrayOf("NONE", "Weapon")
        fun name(e: Int) : String = names[e]
    }
}
