// automatically generated by the FlatBuffers compiler, do not modify

/**
 * The possible monster colors
 */
export enum Color {
  /**
   * Should be rendered the same color as blood
   */
  Red = 0,

  /**
   * Any green will do
   */
  Green = 1,

  /**
   * Must be `#89CFF0`
   */
  Blue = 2
}
